### ISSUE TITLE
do_sqlite3:0.10.14 - LoadError: "cannot load such file -- do_sqlite3/2.1/do_sqlite3"

### ISSUE THREAD

**Issue by volisoft** [datamapper/do#75] opened 2015-01-02 09:15 UTC
Environment: 
RubyInstaller 2.1.5
do_sqlite3:0.10.14

Stack trace:

D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/do_sqlite3-0.10.6-x86-mingw32/lib/do_sqlite3.rb:31:in `require': cannot load such file -- do_sqlite3/2.1/do_sqlite3 (LoadError)
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/do_sqlite3-0.10.6-x86-mingw32/lib/do_sqlite3.rb:31:in `rescue in <top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/do_sqlite3-0.10.6-x86-mingw32/lib/do_sqlite3.rb:26:in `<top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/dm-sqlite-adapter-1.2.0/lib/dm-sqlite-adapter/adapter.rb:1:in `require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/dm-sqlite-adapter-1.2.0/lib/dm-sqlite-adapter/adapter.rb:1:in `<top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/dm-sqlite-adapter-1.2.0/lib/dm-sqlite-adapter.rb:1:in `require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/dm-sqlite-adapter-1.2.0/lib/dm-sqlite-adapter.rb:1:in `<top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `each'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `block in require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `each'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler.rb:134:in `require'
        from D:/work/workspace/passtor/config/boot.rb:8:in `<top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/padrino-core-0.12.4/lib/padrino-core/cli/launcher.rb:25:in `require'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/padrino-core-0.12.4/lib/padrino-core/cli/launcher.rb:25:in `start'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/lib/ruby/gems/2.1.0/gems/padrino-core-0.12.4/bin/padrino:9:in `<top (required)>'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/bin/padrino:23:in `load'
        from D:/programs/development/ruby-2.1.4-x64-mingw32/bin/padrino:23:in `<main>'

**Comment by dbussink** [comment] 2015-01-24 11:38
Duplicate of #72

**Closed by dbussink** 2015-01-24 11:38 UTC
